version: '2'
services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./initdb.sh:/docker-entrypoint-initdb.d/init-wmrug-db.sh
  app:
    build: .
    image: pads/rails-docker-wmrug:1.0.0
    command: bin/rails server --port 3000 --binding 0.0.0.0
    environment:
      RAILS_ENV: production
      RACK_ENV: production
      BUNDLE_WITHOUT: "test:development"
    ports:
      - "3000:3000"
    links:
      - db
    volumes:
      - .:/wmrug
  web:
    image: nginx:latest
    ports:
      - "80:80"
    links:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
