version: '2'
services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./initdb.sh:/docker-entrypoint-initdb.d/init-wmrug-db.sh
  email:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"
  selenium:
    image: selenium/standalone-firefox-debug:2.53.0
    environment:
      no_proxy: localhost
    ports:
      - "4444:4444"
      - "5900:5900"
  web:
    build: .
    image: pads/rails-docker-wmrug:latest
    command: bin/rails server --port 3000 --binding 0.0.0.0
    ports:
      - "3000:3000"
    links:
      - db
      - email
      - selenium
    volumes:
      - .:/wmrug
